import BinaryHeap.CompleteTree.HeapProofs.EmptyIsHeap
import BinaryHeap.CompleteTree.HeapProofs.HeapPush
import BinaryHeap.CompleteTree.HeapProofs.HeapUpdateRoot
import BinaryHeap.CompleteTree.HeapProofs.HeapUpdateAt
import BinaryHeap.CompleteTree.HeapProofs.HeapPop
import BinaryHeap.CompleteTree.HeapProofs.HeapRemoveAt
